version: 2
updates:
- package-ecosystem: maven
  directory: "/msal-obo-sample"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/msal-web-sample"
  schedule:
    interval: daily
  open-pull-requests-limit: 10